import Head from 'next/head'
import {
  Container,
  Main,
  Title,
  Description,
  CodeTag,
} from '../components/sharedstyles'
import useSWR from 'swr'
import {useRouter} from "next/router"
import BookList from '../components/BookList'


//function to fetch a particular url and return the data as json
const fetcher = url => fetch(url).then(r => r.json())

export default function BookDetail() {
    const router = useRouter() // get access to our router object
    const {title} = router.query //gives us access to the end of the url
    //localhost:3000/Lolita -> title = "Lolita"



  //first param is the path of the api endpoint (what will be fetched)
  //second param is the fetcher function that should execute to get the data
  //if it works, data is full and error is false
  //if it fails, data is undefined and error is true

  //use back ticks so we can use string manipulation
  const { data, error } = useSWR(`api/books/${title}`, fetcher)

  //if the API encounters an error, this will render
  if (error) {
    return <Main>Error!</Main>
  }

  //if the data has not come back yet, load this
  if (!data) {
    return <Main>
      Loading...
    </Main>
  }

  // selected book so that variables can be accessed 
  const book = data[0]

  //if the data comes back as expected, this renders
  return (
    <Container>
      {/* use nextjs to add html metadata to each page */}
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Main>
        {/* {JSON.stringify(data)} */}
        <h1>Title: {book.title}</h1>
        <h2>Author: {book.author}</h2>
        <h2>Country: {book.country}</h2>
        <h2>Image Link: {book.imageLink}</h2>
        <h2>Language: {book.language}</h2>
        <h2>Link: {book.link}</h2>
        <h2>Pages: {book.pages}</h2>
        <h2>Year: {book.year}</h2>
      </Main>
    </Container>
  )
}
